# Generated by Django 4.0.6 on 2022-07-14 15:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=6)),
                ('games', models.ManyToManyField(related_name='rent_accounts', to='games.game')),
            ],
        ),
    ]
