# Generated by Django 4.0.6 on 2022-07-13 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_alter_platform_name'),
        ('rent_accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaccount',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_accounts', to='platforms.platform'),
        ),
    ]
