# Generated by Django 4.0.6 on 2022-07-12 21:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rent_accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("reseted", models.BooleanField(default=False)),
                (
                    "rent_accounts",
                    models.ManyToManyField(
                        related_name="rent_accounts", to="rent_accounts.rentaccount"
                    ),
                ),
            ],
        ),
    ]
