# Generated by Django 4.0.6 on 2022-07-15 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rent_accounts', '0002_initial'),
        ('rents_history', '0003_alter_renthistory_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renthistory',
            name='rent_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_histories', to='rent_accounts.rentaccount'),
        ),
        migrations.AlterField(
            model_name='renthistory',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_histories', to=settings.AUTH_USER_MODEL),
        ),
    ]
