# Generated by Django 4.0.6 on 2022-07-15 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents_history', '0004_alter_renthistory_rent_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renthistory',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 15, 16, 48, 23, 819887)),
        ),
    ]
