# Generated by Django 4.0.6 on 2022-07-15 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents_history', '0005_alter_renthistory_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renthistory',
            old_name='price',
            new_name='total_price',
        ),
        migrations.AlterField(
            model_name='renthistory',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 15, 19, 44, 1, 137693)),
        ),
    ]
