# Generated by Django 4.0.6 on 2022-07-16 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents_history', '0006_rename_price_renthistory_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renthistory',
            name='return_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='renthistory',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 15, 22, 16, 3, 448060)),
        ),
    ]
