# Generated by Django 4.0.6 on 2022-07-20 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents_history', '0018_alter_renthistory_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renthistory',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 13, 2, 7, 953922)),
        ),
    ]
