# Generated by Django 4.0.6 on 2022-07-20 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents_history', '0019_alter_renthistory_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renthistory',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 19, 38, 23, 124552)),
        ),
    ]
