# Generated by Django 4.0.6 on 2022-07-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_platform_icon'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(related_name='platforms', to='platforms.platform'),
        ),
    ]
