# Generated by Django 4.0.6 on 2022-07-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_api_id',
            field=models.IntegerField(),
        ),
    ]
