# Generated by Django 4.0.6 on 2022-07-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_api_id',
            field=models.IntegerField(),
        ),
    ]
