# Generated by Django 4.0.6 on 2022-07-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='icon',
            field=models.CharField(default='teste', max_length=40),
            preserve_default=False,
        ),
    ]
